const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_SERVER = 500;
const FORBIDDEN = 403;
const CONFLICT = 409;
const UNAUTHORIZED = 401;
const OK = 200;
const CREATED = 201;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_SERVER,
  FORBIDDEN,
  UNAUTHORIZED,
  CONFLICT,
  OK,
  CREATED,
};
